%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Copyright (C) rtQC Dev-Team
%
% This program is free software; you can redistribute it and/or
% modify it under the terms of the GNU General Public License
% as published by the Free Software Foundation; either version 3
% of the License, or (at your option) any later version.
%
% This program is distributed in the hope that it will be useful,
% but WITHOUT ANY WARRANTY; without even the implied warranty of
% MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
% GNU General Public License for more details.
%
% You should have received a copy of the GNU General Public License
% along with this program; if not, write to the Free Software
% Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307,USA.
%
% Author: Stephan Heunis, <j.s.heunis@tue.nl>, 2018
%
% Function gui_setup
%
% Description:
%
% Parameters:
%
% Returns:
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

% Create tabs
gui_data.tgroup = uitabgroup('Parent', fig,...
    'SelectionChangedFcn', @tabChangedCallback);
gui_data.tab_info = uitab('Parent', gui_data.tgroup, 'Title', 'Info');
gui_data.tab_pre = uitab('Parent', gui_data.tgroup, 'Title', 'Pre-NF QC');
gui_data.tab_online = uitab('Parent', gui_data.tgroup, 'Title', 'Online QC');
gui_data.tab_post = uitab('Parent', gui_data.tgroup, 'Title', 'Post-NF QC');

% Set variable values
gui_data.spm_dir = '/Users/jheunis/Documents/MATLAB/spm12'; %%%%%% USER SPECIFIED
gui_data.current_dir = mfilename('fullpath');
gui_data.folders = regexp(gui_data.current_dir, filesep, 'split');
gui_data.root_dir = gui_data.folders{1};
for i = 2:(numel(gui_data.folders)-2)
    gui_data.root_dir = [gui_data.root_dir filesep gui_data.folders{i}];
end

gui_data.small_font_size = 10;
gui_data.standard_font_size = 13;
gui_data.button_font_size = 13;
gui_data.large_font_size = 24;
gui_data.axes_font_size = 12;
gui_data.vals_font_size = 16;
gui_data.Ndims = [50 50 50];
gui_data.slice_number = 20;
gui_data.FD_threshold = 1; % in mm
gui_data.ax_volumes_title = 'Realigned volume';
gui_data.ax_FD_title = 'Framewise displacement (FD)';
gui_data.ax_globalZ_title = 'Global Z';
gui_data.ax_tSNR_title = 'tSNR';
gui_data.ax_thePlot_title = 'The Plot';


% Create UIcontrols for INFO tab
gui_data.panel_main = uipanel('Parent', gui_data.tab_info,...
    'Title','',...
    'Position',[.25 .15 .5 .7],...
    'fontsize', gui_data.large_font_size);
gui_data.ax1 = axes('Parent', gui_data.panel_main,...
    'Position',[.2 .15 .6 .6]);
gui_data.txt_rtQc = uicontrol('Parent', gui_data.panel_main,...
    'Style','text',...
    'String','rtQC',...
    'Units', 'Normalized',...
    'Position',[0.4 0.85 0.2 0.1],...
    'fontsize', gui_data.large_font_size);
gui_data.txt_rtQcsub = uicontrol('Parent', gui_data.panel_main,...
    'Style','text',...
    'String','An open-source collaborative framework for quality control methods in real-time fMRI',...
    'Units', 'Normalized',...
    'Position',[0.02 0.8 0.96 0.05],...
    'fontsize', gui_data.standard_font_size);
gui_data.pb_help = uicontrol('Parent', gui_data.panel_main,...
    'Style', 'push',...
    'String', 'github', ...
    'Units', 'Normalized',...
    'Position', [0.4 0.02 0.2 0.1],...
    'CallBack', @linkToGithub, ...
    'UserData', 0,...
    'fontsize', gui_data.button_font_size);
gui_data.img_fn = 'brain.png';
brain_img = imread(which(gui_data.img_fn));
image(gui_data.ax1, brain_img)
removeAxesTicks(gui_data.ax1);

% Create UIcontrols for PRE-NF QC tab

% --- Create UIcontrols for ONLINE QC tab ---
% Create panels
gui_data.panel_settings = uipanel('Parent', gui_data.tab_online,...
    'Title','Settings',...
    'Position',[.02 .7 .36 .28],...
    'fontsize', gui_data.standard_font_size);
gui_data.panel_controls = uipanel('Parent', gui_data.tab_online,...
    'Title','Controls',...
    'Position',[.02 .54 .36 .14],...
    'fontsize', gui_data.standard_font_size);
gui_data.panel_volumes = uipanel('Parent', gui_data.tab_online,...
    'Title','Real-time Volume Display',...
    'Position',[.02 .02 .36 .49],...
    'fontsize', gui_data.standard_font_size);
gui_data.panel_rtvalues = uipanel('Parent', gui_data.tab_online,...
    'Title','Real-time Metrics',...
    'Position',[.4 .8 .58 .18],...
    'fontsize', gui_data.standard_font_size);
gui_data.panel_rtplots = uipanel('Parent', gui_data.tab_online,...
    'Title','Real-time QC Display',...
    'Position',[.4 .02 .58 .76],...
    'fontsize', gui_data.standard_font_size);
% Settings panel UIControls
gui_data.txt_structural = uicontrol('Parent', gui_data.panel_settings,...
    'Style','text',...
    'String','Structural .nii',...
    'Units', 'Normalized',...
    'Position',[0.02 0.82 0.15 0.12],...
    'HorizontalAlignment', 'left',...
    'fontsize', gui_data.small_font_size);
gui_data.edit_structural = uicontrol('Parent', gui_data.panel_settings,...
    'Style', 'edit',...
    'String', '', ...
    'Units', 'Normalized',...
    'Position', [0.18 0.82 0.73 0.12],...
    'CallBack', @editStructural, ...
    'HorizontalAlignment', 'left',...
    'fontsize', gui_data.button_font_size);
gui_data.pb_structural = uicontrol('Parent', gui_data.panel_settings,...
    'Style', 'push',...
    'String', '...', ...
    'Units', 'Normalized',...
    'Position', [0.92 0.82 0.06 0.12],...
    'CallBack', @setStructural, ...
    'UserData', 0,...
    'fontsize', gui_data.button_font_size);
gui_data.txt_functional = uicontrol('Parent', gui_data.panel_settings,...
    'Style','text',...
    'String','Functional .nii',...
    'Units', 'Normalized',...
    'Position',[0.02 0.66 0.15 0.12],...
    'HorizontalAlignment', 'left',...
    'fontsize', gui_data.small_font_size);
gui_data.edit_functional = uicontrol('Parent', gui_data.panel_settings,...
    'Style', 'edit',...
    'String', '', ...
    'Units', 'Normalized',...
    'Position', [0.18 0.66 0.73 0.12],...
    'CallBack', @editFunctional, ...
    'HorizontalAlignment', 'left',...
    'fontsize', gui_data.button_font_size);
gui_data.pb_functional = uicontrol('Parent', gui_data.panel_settings,...
    'Style', 'push',...
    'String', '...', ...
    'Units', 'Normalized',...
    'Position', [0.92 0.66 0.06 0.12],...
    'CallBack', @setFunctional, ...
    'UserData', 0,...
    'fontsize', gui_data.button_font_size);

gui_data.txt_fd_threshold = uicontrol('Parent', gui_data.panel_settings,...
    'Style','text',...
    'String','FD Threshold',...
    'Units', 'Normalized',...
    'Position',[0.02 0.5 0.15 0.12],...
    'HorizontalAlignment', 'left',...
    'fontsize', gui_data.small_font_size);
gui_data.edit_fd_threshold = uicontrol('Parent', gui_data.panel_settings,...
    'Style', 'edit',...
    'String', num2str(gui_data.FD_threshold), ...
    'Units', 'Normalized',...
    'Position', [0.18 0.5 0.1 0.12],...
    'CallBack', @editFDthreshold, ...
    'HorizontalAlignment', 'right',...
    'fontsize', gui_data.button_font_size);



% RT controls panel UIcontrols
gui_data.pb_initialize = uicontrol('Parent', gui_data.panel_controls,...
    'Style', 'push',...
    'String', 'INITIALIZE', ...
    'Units', 'Normalized',...
    'Position', [0.05 0.3 0.25 0.45],...
    'CallBack', @initialize, ...
    'UserData', 0,...
    'fontsize', gui_data.button_font_size);
gui_data.pb_startRT = uicontrol('Parent', gui_data.panel_controls,...
    'Style', 'push',...
    'String', 'START', ...
    'Units', 'Normalized',...
    'Position', [0.35 0.3 0.25 0.45],...
    'CallBack', @startRT, ...
    'UserData', 0,...
    'fontsize', gui_data.button_font_size);
gui_data.pb_stopRT = uicontrol('Parent', gui_data.panel_controls,...
    'Style', 'push',...
    'String', 'STOP', ...
    'Units', 'Normalized',...
    'Position', [0.65 0.3 0.25 0.45],...
    'CallBack', @stopRT, ...
    'UserData', 0,...
    'fontsize', gui_data.button_font_size);

% RT values panel UIcontrols
gui_data.txt_Nvolume = uicontrol('Parent', gui_data.panel_rtvalues,...
    'Style','text',...
    'String','Acquired volumes:  0',...
    'Units', 'Normalized',...
    'Position',[0.05 0.65 0.4 0.2],...
    'HorizontalAlignment', 'left',...
    'fontsize', gui_data.vals_font_size);
gui_data.txt_Nvolume_valid = uicontrol('Parent', gui_data.panel_rtvalues,...
    'Style','text',...
    'String','Valid volumes:  0',...
    'Units', 'Normalized',...
    'Position',[0.05 0.35 0.4 0.2],...
    'HorizontalAlignment', 'left',...
    'fontsize', gui_data.vals_font_size);
gui_data.txt_fdsum = uicontrol('Parent', gui_data.panel_rtvalues,...
    'Style','text',...
    'String','Total FD:  0',...
    'Units', 'Normalized',...
    'Position',[0.5 0.65 0.65 0.2],...
    'HorizontalAlignment', 'left',...
    'fontsize', gui_data.vals_font_size);
gui_data.txt_fdave = uicontrol('Parent', gui_data.panel_rtvalues,...
    'Style','text',...
    'String','Mean FD:  0',...
    'Units', 'Normalized',...
    'Position',[0.5 0.35 0.65 0.2],...
    'HorizontalAlignment', 'left',...
    'fontsize', gui_data.vals_font_size);


gui_data.txt_plane = uicontrol('Parent', gui_data.panel_volumes,...
    'Style','text',...
    'String','Change plane',...
    'Units', 'Normalized',...
    'Position',[0.07 0.1 0.3 0.12],...
    'HorizontalAlignment', 'left',...
    'fontsize', gui_data.standard_font_size);
gui_data.popup_setDim = uicontrol('Parent', gui_data.panel_volumes,...
    'Style', 'popup',...
    'String', {'dim1 (X)','dim2 (Y)','dim3 (Z)'},...
    'Units', 'Normalized',...
    'Position', [0.04 0.01 0.22 0.12],...
    'Value', 3,...
    'Callback', @setDim);
gui_data.txt_slice = uicontrol('Parent', gui_data.panel_volumes,...
    'Style','text',...
    'String',['Change slice: #' num2str(gui_data.slice_number)],...
    'Units', 'Normalized',...
    'Position',[0.37 0.1 0.3 0.12],...
    'HorizontalAlignment', 'left',...
    'fontsize', gui_data.standard_font_size);
gui_data.sld_slice = uicontrol('Parent', gui_data.panel_volumes,...
    'Style', 'slider',...
    'Units', 'Normalized',...
    'Position', [0.34 0.01 0.3 0.12],...
    'Min',1,...
    'Max',gui_data.Ndims(gui_data.popup_setDim.Value),...
    'Value',gui_data.slice_number,...
    'SliderStep', [1/gui_data.Ndims(gui_data.popup_setDim.Value) 1/gui_data.Ndims(gui_data.popup_setDim.Value)],...
    'Callback', @changeSlice);
gui_data.txt_img = uicontrol('Parent', gui_data.panel_volumes,...
    'Style','text',...
    'String','Change image',...
    'Units', 'Normalized',...
    'Position',[0.72 0.1 0.3 0.12],...
    'HorizontalAlignment', 'left',...
    'fontsize', gui_data.standard_font_size);
gui_data.popup_setImg = uicontrol('Parent', gui_data.panel_volumes,...
    'Style', 'popup',...
    'String', {'fMRI','tSNR'},...
    'Units', 'Normalized',...
    'Position', [0.71 0.01 0.2 0.12],...
    'Value', 1,...
    'Callback', @changeImg);

% RT plots panel UIcontrols and axes

gui_data.ax_volumes = axes('Parent', gui_data.panel_volumes,...
    'Position',[.2 .28 .6 .62],...
    'Color', 'k',...
    'FontSize', gui_data.axes_font_size);
gui_data.ax_volumes.Title.String = gui_data.ax_volumes_title;

gui_data.ax_FD = axes('Parent', gui_data.panel_rtplots,...
    'Position',[.1 .85 .8 .12],...
    'Color', 'k',...
    'FontSize', gui_data.axes_font_size ,...
    'XGrid', 'on',...
    'YGrid', 'on');
gui_data.ax_FD.Title.String = gui_data.ax_FD_title;
gui_data.ax_FD.YLabel.String = 'mm';

gui_data.ax_globalZ = axes('Parent', gui_data.panel_rtplots,...
    'Position',[.1 .69 .8 .12],...
    'Color', 'k',...
    'FontSize', gui_data.axes_font_size ,...
    'XGrid', 'on',...
    'YGrid', 'on');
gui_data.ax_globalZ.Title.String = gui_data.ax_globalZ_title;
gui_data.ax_globalZ.YLabel.String = 'a.u.';

gui_data.ax_tSNR = axes('Parent', gui_data.panel_rtplots,...
    'Position',[.1 .53 .8 .12],...
    'Color', 'k',...
    'FontSize', gui_data.axes_font_size ,...
    'XGrid', 'on',...
    'YGrid', 'on',...
    'Title',gui_data.ax_tSNR_title);
gui_data.ax_tSNR.Title.String = gui_data.ax_tSNR_title;
gui_data.ax_tSNR.YLabel.String = 'a.u.';

gui_data.ax_thePlot = axes('Parent', gui_data.panel_rtplots,...
    'Position',[.1 .04 .8 .45],...
    'Color', 'k',...
    'FontSize', gui_data.axes_font_size);
gui_data.ax_thePlot.Title.String = gui_data.ax_thePlot_title;
gui_data.ax_thePlot.YLabel.String = 'voxels';
gui_data.ax_thePlot.XLabel.String = 'Volume #';

removeAxesXTickLabels(gui_data.ax_FD);
removeAxesXTickLabels(gui_data.ax_volumes);
removeAxesXTickLabels(gui_data.ax_globalZ);
removeAxesXTickLabels(gui_data.ax_tSNR);



% --- Create UIcontrols for POST-NF QC tab ---


% Save GUI data
guidata(fig, gui_data)


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Helper functions

function removeAxesTicks(ax)
set(ax,'xtick',[])
set(ax,'xticklabel',[])
set(ax,'ytick',[])
set(ax,'yticklabel',[])
set(ax,'ztick',[])
set(ax,'zticklabel',[])
end

function removeAxesXTickLabels(ax)
set(ax,'xticklabel',[])
end
